### PR TITLE
Support-winarm64

### PR DESCRIPTION
**Pull request by howmanysmall**
This should just add windows arm64 support.

### CODE REVIEW

**Review by howmanysmall — COMMENTED** [review]
Ignore the horrendous commits, I was just testing to see if I could build it locally first.

**Comment by howmanysmall** [comment]
I also don't know if I got it building for arm64, if you could check that, that would be sweet.

**Comment by JohnnyMorganz** [comment]
Apologies for the delay!

This change isn't really any different than https://github.com/JohnnyMorganz/luau-lsp/pull/753/files

It is still running on a `windows-latest` runner, which is x86_64 not arm, hence it will not build for ARM

**Comment by howmanysmall** [comment]
Unfortunate. Any way to get the extension building for ARM64 at all, since that would be fine even if it's emulated.

**Comment by JohnnyMorganz** [comment]
Do windows ARM pcs support emulation of x86_64 binaries by default? I'm unfamiliar with this space

If so, then happy to add arm as an extra code target for the x86_64 version

**Comment by howmanysmall** [comment]
yeah it's prism emulation

**Comment by JohnnyMorganz** [comment]
Closed in favour of #682 as it reuses the single artifact whilst this one would require a new rebuild

**Pull request closed without merging**
