### PR TITLE
Add RBXScriptSignal:Once

### PR DESCRIPTION
**Pull request by Baileyeatspizza**
Attempts to fix 
image

### CODE REVIEW

**Review by JohnnyMorganz — CHANGES_REQUESTED** [review]
Please could you edit https://github.com/JohnnyMorganz/luau-lsp/blob/main/scripts/dumpRobloxTypes.py#L256 and then regenerate by running `python dumpRobloxTypes.py > globalTypes.d.lua` as this file is autogenerated

**Comment by Baileyeatspizza** [comment]
@JohnnyMorganz done

**Review by JohnnyMorganz — APPROVED** [review]
Thanks!

**Comment by JohnnyMorganz** [comment]
Sorry, looks like this change actually broke definitions, but CI didn't go red.
image

Will need to revert

**Pull request merged**
