### PR TITLE
Support Windows ARM64

### LINKED ISSUE #673: Support Windows ARM for the VS Code Extension
Not able to install the VS Code LSP on a Windows ARM laptop.

I'm directed to this URL on the extension page: https://aka.ms/vscode-platform-specific-extensions

Screenshot:
Screenshot

### PR DESCRIPTION
**Pull request by dig1t**
Adds `win32-arm64` as a platform target when publishing to vs marketplace.
Closes #673.

### CODE REVIEW

**Comment by JohnnyMorganz** [comment]
Do we not need to also change compilation to support ARM?

**Comment by dig1t** [comment]
I'm not sure it has to be updated.
I successfully built the server and extension multiple times on an arm machine and also ran the release action on a separate repo and was able to work on the published extension the same machine.

**Comment by JohnnyMorganz** [comment]
That makes sense if you built it on an arm machine, but IIRC the github action runners are x86_64, and we have no cross compiling set up.

I don't think GitHub has (free) windows arm runners

**Comment by howmanysmall** [comment]
It does have free ones. I've been doing it and my money has stayed the same.

**Comment by JohnnyMorganz** [comment]
Happy to accept a PR to add windows ARM machines to the release pipeline!

**Comment by howmanysmall** [comment]
if i can figure it out yeah i'll do it

**Review by JohnnyMorganz — APPROVED** [review]
Thanks, going to merge this assuming emulation will allow it to work

**Pull request merged**
